name: dotnet-build-and-pack

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory for the job. Defaults to '.' which is the root of the repository. Do not include trailing '/'"
        required: false
        type: string
        default: "."
      os:
        required: false
        type: string
        default: ubuntu-latest
      dotnet-version:
        required: false
        type: string
        default: 9.0.x
      package-version:
        required: true
        type: string
      package-artifact-name:
        description: "Name of the artifact to upload to github build artifacts"
        required: false
        type: string
        default: "packages"
      add-assembly-version:
        description: "Should only include assembly version on main branch"
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  dotnet-build-and-package:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            aka.ms:443
            api.nuget.org:443
            builds.dotnet.microsoft.com:443
            dc.services.visualstudio.com:443
            dotnetcli.azureedge.net:443
            github.com:443

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup .NET SDK ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Cache .NET packages
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # 5.0.3
        with:
          path: ~/.nuget/packages # Path to the NuGet package cache
          key: ${{ inputs.os }}-${{ inputs.dotnet-version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ inputs.os }}-${{ inputs.dotnet-version }}-nuget-

      - name: Restore packages
        working-directory: ${{ inputs.working-directory }}
        run: dotnet restore --use-lock-file

      # Only include assembly version on main branch
      - name: Package with assembly number
        if: ${{ inputs.add-assembly-version }}
        working-directory: ${{ inputs.working-directory }}
        run: >
          dotnet pack
          --no-restore
          --configuration Release
          --output build-packages
          /p:Version=${{ inputs.package-version }}
          /p:FileVersion=${{ inputs.package-version }}
          /p:AssemblyVersion=${{ inputs.package-version }}
          /p:AssemblyInformationalVersion=${{ inputs.package-version }}

      # Packaging step for non-main branches (without AssemblyVersion)
      - name: Package without assembly number
        if: ${{ !inputs.add-assembly-version }}
        working-directory: ${{ inputs.working-directory }}
        run: >
          dotnet pack
          --no-restore
          --configuration Release
          --output build-packages
          /p:Version=${{ inputs.package-version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ inputs.package-artifact-name }}
          path: |
            ${{ inputs.working-directory }}/build-packages/*.nupkg
            ${{ inputs.working-directory }}/build-packages/*.snupkg
          if-no-files-found: error
